import withAuth from "@/hoc/withAuth";
import Head from "next/head";
import dynamic from "next/dynamic";

const HomeLayout = dynamic(() => import("@/components/layout/HomeLayout"));

function Home() {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div>Home</div>
            </main>
        </>
    );
}

export default withAuth(Home, {
    public: true,
    Layout: HomeLayout,
});
